Pinknose.DistributedWorkers: Pinknose.DistributedWorkers.MessageQueues.MessageQueue Class Reference
Pinknose.DistributedWorkers.MessageQueues.MessageQueue Class Reference
Abstraction of a RabbitMQ queue. This message queue can be written to, but cannot be read from.
Public Member Functions
void Dispose ()
void Purge ()
void RespondToMessage (MessageEnvelope originalMessageEnvelope, MessageBase responseMessage, EncryptionOption encryptionOption)
void Write (MessageBase message, EncryptionOption encryptionOptions, MessageTagCollection tags)
void Write (MessageBase message, IBasicProperties basicProperties, EncryptionOption encryptionOptions, MessageTagCollection tags)
void WriteToBoundExchange (MessageBase message, EncryptionOption encryptionOption, MessageTagCollection tags)
Public Attributes
string Name => queueInfo.QueueName
Returns the name of the queue.
int QueueCount => (int)Channel.MessageCount(Name)
int ConsumerCount => (int)Channel.ConsumerCount(Name)
Protected Member Functions
virtual void Dispose (bool disposing)
Properties
IModel Channel [get, set]
Detailed Description
Abstraction of a RabbitMQ queue. This message queue can be written to, but cannot be read from.
Definition at line 39 of file MessageQueue.cs.
Member Function Documentation
Dispose() [1/2]
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Dispose ()
Definition at line 72 of file MessageQueue.cs.
Dispose() [2/2]
virtual void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Dispose (bool disposing) protected virtual
Reimplemented in Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.
Definition at line 211 of file MessageQueue.cs.
Purge()
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Purge ()
RespondToMessage()
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage (MessageEnvelope originalMessageEnvelope, MessageBase responseMessage, EncryptionOption encryptionOption)
Definition at line 82 of file MessageQueue.cs.
References Pinknose.DistributedWorkers.Messages.MessageEnvelope.BasicProperties, Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Channel, Pinknose.DistributedWorkers.Messages.MessageEnvelope.SenderName, Pinknose.DistributedWorkers.Messages.MessageEnvelope.Serialize(), and Pinknose.DistributedWorkers.Messages.MessageEnvelope.WrapMessage().
Write() [1/2]
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Write (MessageBase message, EncryptionOption encryptionOptions, MessageTagCollection tags)
Definition at line 113 of file MessageQueue.cs.
Referenced by Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Write(), and Pinknose.DistributedWorkers.MessageQueues.MessageQueue.WriteToBoundExchange().
Write() [2/2]
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Write (MessageBase message, IBasicProperties basicProperties, EncryptionOption encryptionOptions, MessageTagCollection tags)
Definition at line 118 of file MessageQueue.cs.
References Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Write().
WriteToBoundExchange()
void Pinknose.DistributedWorkers.MessageQueues.MessageQueue.WriteToBoundExchange (MessageBase message, EncryptionOption encryptionOption, MessageTagCollection tags)
Definition at line 128 of file MessageQueue.cs.
References Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Write().
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToSubscriptionQueues().
Member Data Documentation
ConsumerCount
int Pinknose.DistributedWorkers.MessageQueues.MessageQueue.ConsumerCount => (int)Channel.ConsumerCount(Name)
Definition at line 63 of file MessageQueue.cs.
Name
string Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Name => queueInfo.QueueName
Returns the name of the queue.
Definition at line 60 of file MessageQueue.cs.
Referenced by Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.BeginFullConsume().
QueueCount
int Pinknose.DistributedWorkers.MessageQueues.MessageQueue.QueueCount => (int)Channel.MessageCount(Name)
Definition at line 62 of file MessageQueue.cs.
Property Documentation
Channel
IModel Pinknose.DistributedWorkers.MessageQueues.MessageQueue.Channel get set protected
Definition at line 65 of file MessageQueue.cs.
Referenced by Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.BeginFullConsume(), and Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage().
The documentation for this class was generated from the following file:
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/MessageQueues/MessageQueue.cs