Pinknose.DistributedWorkers: Pinknose.DistributedWorkers.Clients.MessageClientBase Class Reference
Pinknose.DistributedWorkers.Clients.MessageClientBase Class Reference abstract
The base class for message clients and servers.
Public Member Functions
void BeginFullWorkConsume (bool autoAcknowledge)
void BeginLimitedWorkConsume (int maxActiveMessages, bool autoAcknowledge)
void BroadcastToAllClients (MessageBase message, EncryptionOption encryptionOption)
Sends the message to all clients.
abstract void Disconnect ()
void Dispose ()
async Task< RpcCallWaitInfo > WriteToClient (MessageClientInfo clientInfo, MessageBase message, int waitTime, EncryptionOption encryptionOptions)
void WriteToClientNoWait (MessageClientInfo clientInfo, MessageBase message, EncryptionOption encryptionOptions)
void WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, params MessageTag[] tags)
void WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, MessageTagCollection tags)
Static Public Member Functions
static CngKey CreateClientKey (ECDiffieHellmanCurve curve)
static byte[] GetRandomBytes (int length)
Public Attributes
string ClientName => ClientInfo.Name
string SystemName => ClientInfo.SystemName
Protected Member Functions
MessageClientBase (MessageClientInfo clientInfo, string rabbitMqServerHostName, string userName, string password)
virtual void Dispose (bool disposing)
void FireAsynchronousExceptionEvent (object sender, AsynchronousExceptionEventArgs eventArgs)
void FireMessageReceivedEvent (MessageReceivedEventArgs eventArgs)
abstract void SendHeartbeat ()
virtual void SetupConnections (TimeSpan timeout, MessageTagCollection subscriptionTags)
async Task< RpcCallWaitInfo > WriteToClient (string clientName, MessageBase message, int waitTime, EncryptionOption encryptionOptions)
void WriteToClientNoWait (string clientName, MessageBase message, EncryptionOption encryptionOptions)
Protected Attributes
readonly Dictionary< string, RpcCallWaitInfo > rpcCallWaitInfo = new Dictionary<string, RpcCallWaitInfo>()
string BroadcastExchangeName => NameHelper.GetBroadcastExchangeName(SystemName)
string DedicatedQueueName => NameHelper.GetDedicatedQueueName(SystemName, ClientName)
string ServerQueueName => NameHelper.GetServerQueueName(SystemName)
string SubscriptionExchangeName => NameHelper.GetSubscriptionExchangeName(SystemName)
string SubscriptionQueueName => NameHelper.GetSubscriptionQueueName(SystemName, ClientName)
string WorkQueueName => NameHelper.GetWorkQueueName(SystemName)
byte[] SignedMessage
Static Protected Attributes
const int HeartbeatTime = 10000
Heartbeat time between clients/server in milliseconds;
static readonly int SharedKeyByteSize = 32
Properties
bool QueuesAreDurable = true [get, set]
bool AutoDeleteQueuesOnClose = false [get, set]
string InternalId [get]
bool IsConnected = false [get, protected set]
IModel Channel [get]
MessageClientInfo ClientInfo [get]
PublicKeystore PublicKeystore [get]
ReadableMessageQueue SubscriptionQueue [get]
ReadableMessageQueue WorkQueue [get]
Events
EventHandler< AsynchronousExceptionEventArgs > AsynchronousException
EventHandler< MessageReceivedEventArgs > MessageReceived
Detailed Description
The base class for message clients and servers.
Definition at line 50 of file MessageClientBase.cs.
Constructor & Destructor Documentation
MessageClientBase()
Pinknose.DistributedWorkers.Clients.MessageClientBase.MessageClientBase (MessageClientInfo clientInfo, string rabbitMqServerHostName, string userName, string password) protected
Definition at line 86 of file MessageClientBase.cs.
Member Function Documentation
BeginFullWorkConsume()
void Pinknose.DistributedWorkers.Clients.MessageClientBase.BeginFullWorkConsume (bool autoAcknowledge)
BeginLimitedWorkConsume()
void Pinknose.DistributedWorkers.Clients.MessageClientBase.BeginLimitedWorkConsume (int maxActiveMessages, bool autoAcknowledge)
BroadcastToAllClients()
void Pinknose.DistributedWorkers.Clients.MessageClientBase.BroadcastToAllClients (MessageBase message, EncryptionOption encryptionOption)
Sends the message to all clients.
Parameters
message
Definition at line 176 of file MessageClientBase.cs.
CreateClientKey()
static CngKey Pinknose.DistributedWorkers.Clients.MessageClientBase.CreateClientKey (ECDiffieHellmanCurve curve) static
Definition at line 41 of file MessageClientBase_Crypto.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientInfo.CreateClientInfo(), and Pinknose.DistributedWorkers.Clients.MessageClientInfo.CreateServerInfo().
Disconnect()
abstract void Pinknose.DistributedWorkers.Clients.MessageClientBase.Disconnect () pure virtual
Implemented in Pinknose.DistributedWorkers.Clients.MessageServer, and Pinknose.DistributedWorkers.Clients.MessageClient.
Dispose() [1/2]
void Pinknose.DistributedWorkers.Clients.MessageClientBase.Dispose ()
Definition at line 210 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.Dispose().
Dispose() [2/2]
virtual void Pinknose.DistributedWorkers.Clients.MessageClientBase.Dispose (bool disposing) protected virtual
Definition at line 278 of file MessageClientBase.cs.
FireAsynchronousExceptionEvent()
void Pinknose.DistributedWorkers.Clients.MessageClientBase.FireAsynchronousExceptionEvent (object sender, AsynchronousExceptionEventArgs eventArgs) protected
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
FireMessageReceivedEvent()
void Pinknose.DistributedWorkers.Clients.MessageClientBase.FireMessageReceivedEvent (MessageReceivedEventArgs eventArgs) protected
Definition at line 299 of file MessageClientBase.cs.
GetRandomBytes()
static byte [] Pinknose.DistributedWorkers.Clients.MessageClientBase.GetRandomBytes (int length) static
Definition at line 53 of file MessageClientBase_Crypto.cs.
SendHeartbeat()
abstract void Pinknose.DistributedWorkers.Clients.MessageClientBase.SendHeartbeat () protected pure virtual
Implemented in Pinknose.DistributedWorkers.Clients.MessageServer, and Pinknose.DistributedWorkers.Clients.MessageClient.
SetupConnections()
virtual void Pinknose.DistributedWorkers.Clients.MessageClientBase.SetupConnections (TimeSpan timeout, MessageTagCollection subscriptionTags) protected virtual
Reimplemented in MessageClientBase< TServerQueue >.
Definition at line 306 of file MessageClientBase.cs.
WriteToClient() [1/2]
async Task<RpcCallWaitInfo> Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToClient (MessageClientInfo clientInfo, MessageBase message, int waitTime, EncryptionOption encryptionOptions)
Definition at line 218 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClient().
WriteToClient() [2/2]
async Task<RpcCallWaitInfo> Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToClient (string clientName, MessageBase message, int waitTime, EncryptionOption encryptionOptions) protected
Definition at line 356 of file MessageClientBase.cs.
WriteToClientNoWait() [1/2]
void Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToClientNoWait (MessageClientInfo clientInfo, MessageBase message, EncryptionOption encryptionOptions)
Definition at line 228 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClientNoWait().
WriteToClientNoWait() [2/2]
void Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToClientNoWait (string clientName, MessageBase message, EncryptionOption encryptionOptions) protected
Definition at line 405 of file MessageClientBase.cs.
WriteToSubscriptionQueues() [1/2]
void Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, MessageTagCollection tags)
Definition at line 241 of file MessageClientBase.cs.
WriteToSubscriptionQueues() [2/2]
void Pinknose.DistributedWorkers.Clients.MessageClientBase.WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, params MessageTag[] tags)
Referenced by Pinknose.DistributedWorkers.Logging.DistributedWorkersSerilogSink.Emit().
Member Data Documentation
BroadcastExchangeName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.BroadcastExchangeName => NameHelper.GetBroadcastExchangeName(SystemName) protected
Definition at line 141 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.BroadcastToAllClients(), and Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
ClientName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.ClientName => ClientInfo.Name
Definition at line 133 of file MessageClientBase.cs.
Referenced by MessageClientBase< TServerQueue >.SetupConnections(), Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Messages.MessageEnvelope.WrapMessage().
DedicatedQueueName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.DedicatedQueueName => NameHelper.GetDedicatedQueueName(SystemName, ClientName) protected
Definition at line 147 of file MessageClientBase.cs.
HeartbeatTime
const int Pinknose.DistributedWorkers.Clients.MessageClientBase.HeartbeatTime = 10000 static protected
Heartbeat time between clients/server in milliseconds;
Definition at line 57 of file MessageClientBase.cs.
rpcCallWaitInfo
readonly Dictionary<string, RpcCallWaitInfo> Pinknose.DistributedWorkers.Clients.MessageClientBase.rpcCallWaitInfo = new Dictionary<string, RpcCallWaitInfo>() protected
Definition at line 61 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClient().
ServerQueueName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.ServerQueueName => NameHelper.GetServerQueueName(SystemName) protected
Definition at line 151 of file MessageClientBase.cs.
Referenced by MessageClientBase< TServerQueue >.SetupConnections().
SharedKeyByteSize
readonly int Pinknose.DistributedWorkers.Clients.MessageClientBase.SharedKeyByteSize = 32 static protected
Definition at line 59 of file MessageClientBase.cs.
SignedMessage
byte [] Pinknose.DistributedWorkers.Clients.MessageClientBase.SignedMessage protected
Definition at line 251 of file MessageClientBase.cs.
SubscriptionExchangeName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.SubscriptionExchangeName => NameHelper.GetSubscriptionExchangeName(SystemName) protected
Definition at line 153 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
SubscriptionQueueName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.SubscriptionQueueName => NameHelper.GetSubscriptionQueueName(SystemName, ClientName) protected
Definition at line 157 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
SystemName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.SystemName => ClientInfo.SystemName
Definition at line 139 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClient().
WorkQueueName
string Pinknose.DistributedWorkers.Clients.MessageClientBase.WorkQueueName => NameHelper.GetWorkQueueName(SystemName) protected
Definition at line 161 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
Property Documentation
AutoDeleteQueuesOnClose
bool Pinknose.DistributedWorkers.Clients.MessageClientBase.AutoDeleteQueuesOnClose = false get set
Definition at line 80 of file MessageClientBase.cs.
Referenced by MessageClientBase< TServerQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
Channel
IModel Pinknose.DistributedWorkers.Clients.MessageClientBase.Channel get protected
Definition at line 143 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.BroadcastToAllClients(), MessageClientBase< TServerQueue >.SetupConnections(), Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClient().
ClientInfo
MessageClientInfo Pinknose.DistributedWorkers.Clients.MessageClientBase.ClientInfo get
Definition at line 145 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.MessageClientBase().
InternalId
string Pinknose.DistributedWorkers.Clients.MessageClientBase.InternalId get
Definition at line 135 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.MessageClientBase().
IsConnected
bool Pinknose.DistributedWorkers.Clients.MessageClientBase.IsConnected = false get protected set
Definition at line 137 of file MessageClientBase.cs.
PublicKeystore
PublicKeystore Pinknose.DistributedWorkers.Clients.MessageClientBase.PublicKeystore get protected
Definition at line 149 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.MessageClientBase().
QueuesAreDurable
bool Pinknose.DistributedWorkers.Clients.MessageClientBase.QueuesAreDurable = true get set
Definition at line 79 of file MessageClientBase.cs.
Referenced by MessageClientBase< TServerQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
SubscriptionQueue
ReadableMessageQueue Pinknose.DistributedWorkers.Clients.MessageClientBase.SubscriptionQueue get protected
Definition at line 155 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToSubscriptionQueues().
WorkQueue
ReadableMessageQueue Pinknose.DistributedWorkers.Clients.MessageClientBase.WorkQueue get protected
Definition at line 159 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections().
Event Documentation
AsynchronousException
EventHandler<AsynchronousExceptionEventArgs> Pinknose.DistributedWorkers.Clients.MessageClientBase.AsynchronousException
Definition at line 125 of file MessageClientBase.cs.
MessageReceived
EventHandler<MessageReceivedEventArgs> Pinknose.DistributedWorkers.Clients.MessageClientBase.MessageReceived
Definition at line 127 of file MessageClientBase.cs.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.FireMessageReceivedEvent().
The documentation for this class was generated from the following files:
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/Clients/MessageClientBase.cs
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/Clients/MessageClientBase_Crypto.cs