Pinknose.DistributedWorkers: Pinknose.DistributedWorkers.Clients.MessageClient Class Reference
Pinknose.DistributedWorkers.Clients.MessageClient Class Reference
Public Member Functions
void Connect (int timeout, params MessageTag[] subscriptionTags)
void Connect (TimeSpan timeout, params MessageTag[] subscriptionTags)
void Connect (TimeSpan timeout, MessageTagCollection subscriptionTags)
override void Disconnect ()
async Task< RpcCallWaitInfo > WriteToServer (MessageBase message, int waitTime, EncryptionOption encryptionOptions)
void WriteToServerNoWait (MessageBase message, EncryptionOption encryptionOptions)
Public Member Functions inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
void BeginFullWorkConsume (bool autoAcknowledge)
void BeginLimitedWorkConsume (int maxActiveMessages, bool autoAcknowledge)
void BroadcastToAllClients (MessageBase message, EncryptionOption encryptionOption)
Sends the message to all clients.
void Dispose ()
async Task< RpcCallWaitInfo > WriteToClient (MessageClientInfo clientInfo, MessageBase message, int waitTime, EncryptionOption encryptionOptions)
void WriteToClientNoWait (MessageClientInfo clientInfo, MessageBase message, EncryptionOption encryptionOptions)
void WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, params MessageTag[] tags)
void WriteToSubscriptionQueues (MessageBase message, EncryptionOption encryptionOption, MessageTagCollection tags)
Protected Member Functions
sealed override void SendHeartbeat ()
Protected Member Functions inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
MessageClientBase (MessageClientInfo clientInfo, string rabbitMqServerHostName, string userName, string password)
virtual void Dispose (bool disposing)
async Task< RpcCallWaitInfo > WriteToClient (string clientName, MessageBase message, int waitTime, EncryptionOption encryptionOptions)
void WriteToClientNoWait (string clientName, MessageBase message, EncryptionOption encryptionOptions)
void FireAsynchronousExceptionEvent (object sender, AsynchronousExceptionEventArgs eventArgs)
void FireMessageReceivedEvent (MessageReceivedEventArgs eventArgs)
virtual void SetupConnections (TimeSpan timeout, MessageTagCollection subscriptionTags)
Additional Inherited Members
Static Public Member Functions inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
static CngKey CreateClientKey (ECDiffieHellmanCurve curve)
static byte[] GetRandomBytes (int length)
Public Attributes inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
string ClientName
string SystemName
Protected Attributes inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
readonly Dictionary< string, RpcCallWaitInfo > rpcCallWaitInfo
string BroadcastExchangeName
string DedicatedQueueName
string ServerQueueName
string SubscriptionExchangeName
string SubscriptionQueueName
string WorkQueueName
byte[] SignedMessage
Static Protected Attributes inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
const int HeartbeatTime
Heartbeat time between clients/server in milliseconds;
static readonly int SharedKeyByteSize
Properties inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
bool QueuesAreDurable [get, set]
bool AutoDeleteQueuesOnClose [get, set]
string InternalId [get]
bool IsConnected [get, protected set]
IModel Channel [get]
MessageClientInfo ClientInfo [get]
PublicKeystore PublicKeystore [get]
ReadableMessageQueue SubscriptionQueue [get]
ReadableMessageQueue WorkQueue [get]
Events inherited from Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >
EventHandler< AsynchronousExceptionEventArgs > AsynchronousException
EventHandler< MessageReceivedEventArgs > MessageReceived
Detailed Description
Definition at line 36 of file MessageClient.cs.
Member Function Documentation
Connect() [1/3]
void Pinknose.DistributedWorkers.Clients.MessageClient.Connect (int timeout, params MessageTag[] subscriptionTags)
Connect() [2/3]
void Pinknose.DistributedWorkers.Clients.MessageClient.Connect (TimeSpan timeout, MessageTagCollection subscriptionTags)
Definition at line 73 of file MessageClient.cs.
References Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.AsynchronousException, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.AutoDeleteQueuesOnClose, Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.BeginFullConsume(), Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.BroadcastExchangeName, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.Channel, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.ClientName, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.DedicatedQueueName, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.FireAsynchronousExceptionEvent(), Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.IsConnected, Pinknose.DistributedWorkers.MessageQueues.ReadableMessageQueue.MessageReceived, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.PublicKeystore, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.QueuesAreDurable, Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.SetupConnections(), and Pinknose.DistributedWorkers.Clients.MessageClient.WriteToServer().
Connect() [3/3]
void Pinknose.DistributedWorkers.Clients.MessageClient.Connect (TimeSpan timeout, params MessageTag[] subscriptionTags)
Disconnect()
override void Pinknose.DistributedWorkers.Clients.MessageClient.Disconnect () virtual
Implements Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.
Definition at line 132 of file MessageClient.cs.
SendHeartbeat()
sealed override void Pinknose.DistributedWorkers.Clients.MessageClient.SendHeartbeat () protected virtual
Implements Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.
Definition at line 159 of file MessageClient.cs.
WriteToServer()
async Task<RpcCallWaitInfo> Pinknose.DistributedWorkers.Clients.MessageClient.WriteToServer (MessageBase message, int waitTime, EncryptionOption encryptionOptions)
Definition at line 137 of file MessageClient.cs.
References Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClient().
Referenced by Pinknose.DistributedWorkers.Clients.MessageClient.Connect().
WriteToServerNoWait()
void Pinknose.DistributedWorkers.Clients.MessageClient.WriteToServerNoWait (MessageBase message, EncryptionOption encryptionOptions)
Definition at line 151 of file MessageClient.cs.
References Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.WriteToClientNoWait().
The documentation for this class was generated from the following file:
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/Clients/MessageClient.cs