Pinknose.DistributedWorkers: Pinknose.DistributedWorkers.Messages.MessageEnvelope Class Reference
Pinknose.DistributedWorkers.Messages.MessageEnvelope Class Reference
Public Member Functions
byte[] Serialize ()
Static Public Member Functions
static MessageEnvelope WrapMessage (MessageBase message, string recipientName, MessageClientBase messageClient, EncryptionOption encryptionOption)
Properties
IBasicProperties BasicProperties = null [get]
ulong DeliveryTag [get]
string Exchange [get]
MessageBase Message = null [get]
string RecipientName [get]
bool Redelivered [get]
PublicationAddress ReplyToAddres [get]
string RoutingKey [get]
string SenderName [get]
SignatureVerificationStatus SignatureVerificationStatus [get]
MessageTag[] Tags [get]
Detailed Description
Definition at line 37 of file MessageEnvelope.cs.
Member Function Documentation
Serialize()
byte [] Pinknose.DistributedWorkers.Messages.MessageEnvelope.Serialize ()
Returns
Message Wrapper Format:
[ Info Bits ][ Info Numbers ][ Sender Name ][ IV - Optional][ Serialized Message (encryption optional)][ Signature ] [ Signature based on this data ]
Definition at line 116 of file MessageEnvelope.cs.
References Pinknose.DistributedWorkers.Messages.MessageEnvelope.Message, and Pinknose.DistributedWorkers.Messages.MessageEnvelope.SenderName.
Referenced by Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage().
WrapMessage()
static MessageEnvelope Pinknose.DistributedWorkers.Messages.MessageEnvelope.WrapMessage (MessageBase message, string recipientName, MessageClientBase messageClient, EncryptionOption encryptionOption) static
Definition at line 87 of file MessageEnvelope.cs.
References Pinknose.DistributedWorkers.Clients.MessageClientBase.ClientName.
Referenced by Pinknose.DistributedWorkers.Clients.MessageClientBase< MessageQueue >.BroadcastToAllClients(), and Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage().
Property Documentation
BasicProperties
IBasicProperties Pinknose.DistributedWorkers.Messages.MessageEnvelope.BasicProperties = null get
Definition at line 69 of file MessageEnvelope.cs.
Referenced by Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage().
DeliveryTag
ulong Pinknose.DistributedWorkers.Messages.MessageEnvelope.DeliveryTag get
Definition at line 70 of file MessageEnvelope.cs.
Exchange
string Pinknose.DistributedWorkers.Messages.MessageEnvelope.Exchange get
Definition at line 71 of file MessageEnvelope.cs.
Message
MessageBase Pinknose.DistributedWorkers.Messages.MessageEnvelope.Message = null get
Definition at line 72 of file MessageEnvelope.cs.
Referenced by Pinknose.DistributedWorkers.Messages.MessageEnvelope.Serialize().
RecipientName
string Pinknose.DistributedWorkers.Messages.MessageEnvelope.RecipientName get
Definition at line 74 of file MessageEnvelope.cs.
Redelivered
bool Pinknose.DistributedWorkers.Messages.MessageEnvelope.Redelivered get
Definition at line 75 of file MessageEnvelope.cs.
ReplyToAddres
PublicationAddress Pinknose.DistributedWorkers.Messages.MessageEnvelope.ReplyToAddres get
Definition at line 76 of file MessageEnvelope.cs.
RoutingKey
string Pinknose.DistributedWorkers.Messages.MessageEnvelope.RoutingKey get
Definition at line 77 of file MessageEnvelope.cs.
SenderName
string Pinknose.DistributedWorkers.Messages.MessageEnvelope.SenderName get
Definition at line 78 of file MessageEnvelope.cs.
Referenced by Pinknose.DistributedWorkers.MessageQueues.MessageQueue.RespondToMessage(), and Pinknose.DistributedWorkers.Messages.MessageEnvelope.Serialize().
SignatureVerificationStatus
SignatureVerificationStatus Pinknose.DistributedWorkers.Messages.MessageEnvelope.SignatureVerificationStatus get
Definition at line 79 of file MessageEnvelope.cs.
Tags
MessageTag [] Pinknose.DistributedWorkers.Messages.MessageEnvelope.Tags get
Definition at line 81 of file MessageEnvelope.cs.
The documentation for this class was generated from the following file:
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/Messages/MessageEnvelope.cs