Pinknose.DistributedWorkers: Pinknose.DistributedWorkers.MessageTags.MessageTag Class Reference
Pinknose.DistributedWorkers.MessageTags.MessageTag Class Reference
Represents a tag that can be used to subscribe to certain messages.
Public Member Functions
MessageTag (string tagName)
override bool Equals (object obj)
bool Equals ([AllowNull] MessageTag other)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static bool operator!= (MessageTag tag1, MessageTag tag2)
static bool operator== (MessageTag tag1, MessageTag tag2)
static MessageTagCollection operator| (MessageTag tag1, MessageTag tag2)
static MessageTagCollection operator| (MessageTagCollection tags, MessageTag tag1)
Properties
string TagName [get]
Detailed Description
Represents a tag that can be used to subscribe to certain messages.
Definition at line 35 of file MessageTag.cs.
Constructor & Destructor Documentation
MessageTag()
Pinknose.DistributedWorkers.MessageTags.MessageTag.MessageTag (string tagName)
Definition at line 39 of file MessageTag.cs.
References Pinknose.DistributedWorkers.MessageTags.MessageTag.TagName.
Member Function Documentation
Equals() [1/2]
bool Pinknose.DistributedWorkers.MessageTags.MessageTag.Equals ([AllowNull] MessageTag other)
Definition at line 69 of file MessageTag.cs.
Equals() [2/2]
override bool Pinknose.DistributedWorkers.MessageTags.MessageTag.Equals (object obj)
Definition at line 64 of file MessageTag.cs.
Referenced by Pinknose.DistributedWorkers.MessageTags.MessageTag.operator!=(), and Pinknose.DistributedWorkers.MessageTags.MessageTag.operator==().
GetHashCode()
override int Pinknose.DistributedWorkers.MessageTags.MessageTag.GetHashCode ()
Definition at line 74 of file MessageTag.cs.
operator!=()
static bool Pinknose.DistributedWorkers.MessageTags.MessageTag.operator!= (MessageTag tag1, MessageTag tag2) static
Definition at line 54 of file MessageTag.cs.
References Pinknose.DistributedWorkers.MessageTags.MessageTag.Equals().
operator==()
static bool Pinknose.DistributedWorkers.MessageTags.MessageTag.operator== (MessageTag tag1, MessageTag tag2) static
Definition at line 59 of file MessageTag.cs.
References Pinknose.DistributedWorkers.MessageTags.MessageTag.Equals().
operator|() [1/2]
static MessageTagCollection Pinknose.DistributedWorkers.MessageTags.MessageTag.operator| (MessageTag tag1, MessageTag tag2) static
Definition at line 84 of file MessageTag.cs.
operator|() [2/2]
static MessageTagCollection Pinknose.DistributedWorkers.MessageTags.MessageTag.operator| (MessageTagCollection tags, MessageTag tag1) static
Definition at line 92 of file MessageTag.cs.
References Pinknose.DistributedWorkers.MessageTags.MessageTagCollection.Add().
ToString()
override string Pinknose.DistributedWorkers.MessageTags.MessageTag.ToString ()
Definition at line 79 of file MessageTag.cs.
Property Documentation
TagName
string Pinknose.DistributedWorkers.MessageTags.MessageTag.TagName get
Definition at line 48 of file MessageTag.cs.
Referenced by Pinknose.DistributedWorkers.MessageTags.MessageTag.MessageTag().
The documentation for this class was generated from the following file:
Pinknose.DistributedWorkers/Pinknose.DistributedWorkers/MessageTags/MessageTag.cs